postgresql:
  enabled: false
postgresql-ha:
  enabled: false
valkey:
  enabled: false
redis:
  enabled: false
redis-cluster:
  enabled: false
mariadb:
  enabled: false
mysql:
  enabled: false

persistence:
  enabled: true
  size: 5Gi

gitea:
  config:
    database:
      DB_TYPE: sqlite3
    admin:
      username: testuser
      password: admin@123
      email: admin@admin.com 